//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MidiBard.Resources
{
    using System;


    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Language
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language()
        {
        }

        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MidiBard2.Resources.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Begin ensemble ready check ähnelt.
        /// </summary>
        internal static string ensemble_begin_ensemble_ready_check
        {
            get
            {
                return ResourceManager.GetString("ensemble begin ensemble ready check", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Assign track to a character. Right click to reset assigned character ähnelt.
        /// </summary>
        internal static string ensemble_combo_tooltip_assign_track_character
        {
            get
            {
                return ResourceManager.GetString("ensemble combo tooltip assign track character", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Draw ensemble timeline on visualizer ähnelt.
        /// </summary>
        internal static string ensemble_config_draw_ensemble_progress_indicator_on_visualizer
        {
            get
            {
                return ResourceManager.GetString("ensemble config Draw ensemble progress indicator on visualizer", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ensemble indicator delay ähnelt.
        /// </summary>
        internal static string ensemble_config_ensemble_indicator_delay
        {
            get
            {
                return ResourceManager.GetString("ensemble config ensemble indicator delay", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Update instrument when begin ensemble ähnelt.
        /// </summary>
        internal static string ensemble_config_update_instrument_when_begin_ensemble
        {
            get
            {
                return ResourceManager.GetString("ensemble config update instrument when begin ensemble", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delete and reset current file config ähnelt.
        /// </summary>
        internal static string ensemble_delete_and_reset_current_file_config
        {
            get
            {
                return ResourceManager.GetString("ensemble delete and reset current file config", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Minimize other clients, right click to restore them. ähnelt.
        /// </summary>
        internal static string ensemble_minimize_other_clients
        {
            get
            {
                return ResourceManager.GetString("ensemble minimize other clients", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mute other clients ähnelt.
        /// </summary>
        internal static string ensemble_mute_other_clients
        {
            get
            {
                return ResourceManager.GetString("ensemble mute other clients", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Open current midi config file directory ähnelt.
        /// </summary>
        internal static string ensemble_open_midi_config_directory
        {
            get
            {
                return ResourceManager.GetString("ensemble open midi config directory", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Open current midi config file ähnelt.
        /// </summary>
        internal static string ensemble_open_midi_config_file
        {
            get
            {
                return ResourceManager.GetString("ensemble open midi config file", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Export to Default Performer ähnelt.
        /// </summary>
        internal static string ensemble_save_default_performers
        {
            get
            {
                return ResourceManager.GetString("ensemble save default performers", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select a song from playlist ähnelt.
        /// </summary>
        internal static string ensemble_select_a_song_from_playlist
        {
            get
            {
                return ResourceManager.GetString("ensemble select a song from playlist", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Stop ensemble ähnelt.
        /// </summary>
        internal static string ensemble_stop_ensemble
        {
            get
            {
                return ResourceManager.GetString("ensemble stop ensemble", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unmute other clients ähnelt.
        /// </summary>
        internal static string ensemble_unmute_other_clients
        {
            get
            {
                return ResourceManager.GetString("ensemble unmute other clients", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Update Instruments, right click to pull back instrument ähnelt.
        /// </summary>
        internal static string ensemble_update_instruments
        {
            get
            {
                return ResourceManager.GetString("ensemble update instruments", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enter to search ähnelt.
        /// </summary>
        internal static string hint_search_textbox
        {
            get
            {
                return ResourceManager.GetString("hint search textbox", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Clear highlighted songs ähnelt.
        /// </summary>
        internal static string icon_button_tooltip_clear_highlighted_songs
        {
            get
            {
                return ResourceManager.GetString("icon button tooltip clear highlighted songs", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Clear Playlist ähnelt.
        /// </summary>
        internal static string icon_button_tooltip_clear_playlist
        {
            get
            {
                return ResourceManager.GetString("icon button tooltip clear playlist", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Double click to clear playlist ähnelt.
        /// </summary>
        internal static string icon_button_tooltip_clearplaylist_tootltip
        {
            get
            {
                return ResourceManager.GetString("icon button tooltip clearplaylist tootltip", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ensemble panel ähnelt.
        /// </summary>
        internal static string icon_button_tooltip_ensemble_panel
        {
            get
            {
                return ResourceManager.GetString("icon button tooltip ensemble panel", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Help ähnelt.
        /// </summary>
        internal static string icon_button_tooltip_help
        {
            get
            {
                return ResourceManager.GetString("icon button tooltip help", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Import midi file
        ///Right click to select file dialog type ähnelt.
        /// </summary>
        internal static string icon_button_tooltip_import_file
        {
            get
            {
                return ResourceManager.GetString("icon button tooltip import file", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Import folder
        ///Imports all midi files in selected folder and it&apos;s all subfolders.
        ///This may take a while when you select a folder that contains multiple layers of subfolders. ähnelt.
        /// </summary>
        internal static string icon_button_tooltip_import_folder
        {
            get
            {
                return ResourceManager.GetString("icon button tooltip import folder", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mini player ähnelt.
        /// </summary>
        internal static string icon_button_tooltip_mini_player
        {
            get
            {
                return ResourceManager.GetString("icon button tooltip mini player", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Music control panel ähnelt.
        /// </summary>
        internal static string icon_button_tooltip_music_control_panel
        {
            get
            {
                return ResourceManager.GetString("icon button tooltip music control panel", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show playlist menu ähnelt.
        /// </summary>
        internal static string icon_button_tooltip_playlist_menu
        {
            get
            {
                return ResourceManager.GetString("icon button tooltip playlist menu", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Search playlist ähnelt.
        /// </summary>
        internal static string icon_button_tooltip_search_playlist
        {
            get
            {
                return ResourceManager.GetString("icon button tooltip search playlist", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Settings panel ähnelt.
        /// </summary>
        internal static string icon_button_tooltip_settings_panel
        {
            get
            {
                return ResourceManager.GetString("icon button tooltip settings panel", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sync all Midibard settings on this pc ähnelt.
        /// </summary>
        internal static string icon_button_tooltip_sync_settings
        {
            get
            {
                return ResourceManager.GetString("icon button tooltip sync settings", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tracks visualization window
        ///Right click to reset visualizer window position ähnelt.
        /// </summary>
        internal static string icon_button_tooltip_visualization
        {
            get
            {
                return ResourceManager.GetString("icon button tooltip visualization", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Following current playback progress ähnelt.
        /// </summary>
        internal static string icon_button_tooltip_visualizer_follow_playback_tooltip
        {
            get
            {
                return ResourceManager.GetString("icon button tooltip visualizer follow playback tooltip", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ImGui file dialog ähnelt.
        /// </summary>
        internal static string imgui_file_dialog
        {
            get
            {
                return ResourceManager.GetString("imgui file dialog", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Chinese Simplified ähnelt.
        /// </summary>
        internal static string language_chs
        {
            get
            {
                return ResourceManager.GetString("language chs", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Chinese Traditional ähnelt.
        /// </summary>
        internal static string language_cht
        {
            get
            {
                return ResourceManager.GetString("language cht", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die English ähnelt.
        /// </summary>
        internal static string language_english
        {
            get
            {
                return ResourceManager.GetString("language english", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die German ähnelt.
        /// </summary>
        internal static string language_german
        {
            get
            {
                return ResourceManager.GetString("language german", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Japanese ähnelt.
        /// </summary>
        internal static string language_japanese
        {
            get
            {
                return ResourceManager.GetString("language japanese", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Load ähnelt.
        /// </summary>
        internal static string menu_item_load_playlist
        {
            get
            {
                return ResourceManager.GetString("menu item load playlist", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Open in file explorer ähnelt.
        /// </summary>
        internal static string menu_item_open_in_file_explorer
        {
            get
            {
                return ResourceManager.GetString("menu item open in file explorer", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Open in text editor ähnelt.
        /// </summary>
        internal static string menu_item_open_in_text_editor
        {
            get
            {
                return ResourceManager.GetString("menu item open in text editor", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Remove from recent list ähnelt.
        /// </summary>
        internal static string menu_item_remove_from_recent_list
        {
            get
            {
                return ResourceManager.GetString("menu item remove from recent list", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save current playlist as... ähnelt.
        /// </summary>
        internal static string menu_label_clone_current_playlist
        {
            get
            {
                return ResourceManager.GetString("menu label clone current playlist", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Close ähnelt.
        /// </summary>
        internal static string menu_label_close
        {
            get
            {
                return ResourceManager.GetString("menu label close", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Copy song name ähnelt.
        /// </summary>
        internal static string menu_label_copy_song_name
        {
            get
            {
                return ResourceManager.GetString("menu label copy song name", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ↓ Move song to bottom ähnelt.
        /// </summary>
        internal static string menu_label_move_song_to_bottom
        {
            get
            {
                return ResourceManager.GetString("menu label move song to bottom", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Move song to position ähnelt.
        /// </summary>
        internal static string menu_label_move_song_to_position
        {
            get
            {
                return ResourceManager.GetString("menu label move song to position", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ↑ Move song to top ähnelt.
        /// </summary>
        internal static string menu_label_move_song_to_top
        {
            get
            {
                return ResourceManager.GetString("menu label move song to top", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Create a new playlist ähnelt.
        /// </summary>
        internal static string menu_label_new_playlist
        {
            get
            {
                return ResourceManager.GetString("menu label new playlist", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Open playlist ähnelt.
        /// </summary>
        internal static string menu_label_open_playlist
        {
            get
            {
                return ResourceManager.GetString("menu label open playlist", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Remove song from playlist ähnelt.
        /// </summary>
        internal static string menu_label_remove_song_from_playlist
        {
            get
            {
                return ResourceManager.GetString("menu label remove song from playlist", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save playlist ähnelt.
        /// </summary>
        internal static string menu_label_save_playlist
        {
            get
            {
                return ResourceManager.GetString("menu label save playlist", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save playlist search results as... ähnelt.
        /// </summary>
        internal static string menu_label_save_search_as_playlist
        {
            get
            {
                return ResourceManager.GetString("menu label save search as playlist", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Send song name to chat ähnelt.
        /// </summary>
        internal static string menu_label_send_song_name_to_chat
        {
            get
            {
                return ResourceManager.GetString("menu label send song name to chat", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sync playlist between clients ähnelt.
        /// </summary>
        internal static string menu_label_sync_playlist
        {
            get
            {
                return ResourceManager.GetString("menu label sync playlist", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Toggle song played status ähnelt.
        /// </summary>
        internal static string menu_label_toggle_song_played_status
        {
            get
            {
                return ResourceManager.GetString("menu label toggle song played status", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Recent playlists ähnelt.
        /// </summary>
        internal static string menu_text_recent_playlist
        {
            get
            {
                return ResourceManager.GetString("menu text recent playlist", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No matching songs. Try change the search filters ähnelt.
        /// </summary>
        internal static string no_matching_songs_try_change_the_search_filters
        {
            get
            {
                return ResourceManager.GetString("no matching songs try change the search filters", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &quot;{0}&quot; is not available now.
        ///Please check log for further error information. ähnelt.
        /// </summary>
        internal static string notice_midi_device_error
        {
            get
            {
                return ResourceManager.GetString("notice midi device error", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Stop event listening on  ähnelt.
        /// </summary>
        internal static string notice_midi_device_stop_listening
        {
            get
            {
                return ResourceManager.GetString("notice midi device stop listening", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die List ordered ähnelt.
        /// </summary>
        internal static string play_mode_list_ordered
        {
            get
            {
                return ResourceManager.GetString("play mode list ordered", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die List repeat ähnelt.
        /// </summary>
        internal static string play_mode_list_repeat
        {
            get
            {
                return ResourceManager.GetString("play mode list repeat", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Random ähnelt.
        /// </summary>
        internal static string play_mode_random
        {
            get
            {
                return ResourceManager.GetString("play mode random", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Single ähnelt.
        /// </summary>
        internal static string play_mode_single
        {
            get
            {
                return ResourceManager.GetString("play mode single", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Single repeat ähnelt.
        /// </summary>
        internal static string play_mode_single_repeat
        {
            get
            {
                return ResourceManager.GetString("play mode single repeat", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ensemble settings ähnelt.
        /// </summary>
        internal static string setting_group_label_ensemble_settings
        {
            get
            {
                return ResourceManager.GetString("setting group label ensemble settings", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die General settings ähnelt.
        /// </summary>
        internal static string setting_group_label_general_settings
        {
            get
            {
                return ResourceManager.GetString("setting group label general settings", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Performance settings ähnelt.
        /// </summary>
        internal static string setting_group_label_performance_settings
        {
            get
            {
                return ResourceManager.GetString("setting group label performance settings", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Anti note stack option ähnelt.
        /// </summary>
        internal static string setting_label_anti_note_stack_loaded_midi
        {
            get
            {
                return ResourceManager.GetString("setting_label_anti_note_stack_loaded_midi", resourceCulture);
            }
        }

        internal static string setting_label_default_instrument
        {
            get
            {
                return ResourceManager.GetString("setting_label_default_instrument", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Auto adapt notes ähnelt.
        /// </summary>
        internal static string setting_label_auto_adapt_notes
        {
            get
            {
                return ResourceManager.GetString("setting label auto adapt notes", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Auto align midi ähnelt.
        /// </summary>
        internal static string setting_label_auto_align_loaded_midi
        {
            get
            {
                return ResourceManager.GetString("setting label auto align loaded midi", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Auto close MidiBard when exiting performance ähnelt.
        /// </summary>
        internal static string setting_label_auto_close_when_performing
        {
            get
            {
                return ResourceManager.GetString("setting_label_auto_close_when_performing", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Auto open MidiBard on startup ähnelt.
        /// </summary>
        internal static string setting_label_auto_open_on_startup
        {
            get
            {
                return ResourceManager.GetString("setting label auto open on startup", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Auto open MidiBard when entering performance ähnelt.
        /// </summary>
        internal static string setting_label_auto_open_when_performing
        {
            get
            {
                return ResourceManager.GetString("setting label auto open when performing", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Auto restart listening ähnelt.
        /// </summary>
        internal static string setting_label_auto_restart_listening
        {
            get
            {
                return ResourceManager.GetString("setting label auto restart listening", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Auto set background frame limit ähnelt.
        /// </summary>
        internal static string setting_label_auto_set_background_frame_limit
        {
            get
            {
                return ResourceManager.GetString("setting label auto set background frame limit", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Auto switch instrument (midi track name) ähnelt.
        /// </summary>
        internal static string setting_label_auto_switch_instrument_bmp
        {
            get
            {
                return ResourceManager.GetString("setting label auto switch instrument bmp", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Auto switch instrument (file name) ähnelt.
        /// </summary>
        internal static string setting_label_auto_switch_instrument_by_file_name
        {
            get
            {
                return ResourceManager.GetString("setting label auto switch instrument by file name", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Auto transpose (file name) ähnelt.
        /// </summary>
        internal static string setting_label_auto_transpose_by_file_name
        {
            get
            {
                return ResourceManager.GetString("setting label auto transpose by file name", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hide player information from UI for recording and screenshots ähnelt.
        /// </summary>
        internal static string setting_label_hide_player_information_from_ui
        {
            get
            {
                return ResourceManager.GetString("setting label hide player information from ui", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Low latency mode ähnelt.
        /// </summary>
        internal static string setting_label_low_latency_mode
        {
            get
            {
                return ResourceManager.GetString("setting label low latency mode", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die MIDI Input ähnelt.
        /// </summary>
        internal static string setting_label_midi_input_device
        {
            get
            {
                return ResourceManager.GetString("setting label midi input device", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Monitor ensemble ähnelt.
        /// </summary>
        internal static string setting_label_monitor_ensemble
        {
            get
            {
                return ResourceManager.GetString("setting label monitor ensemble", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Played song highlight color ähnelt.
        /// </summary>
        internal static string setting_label_played_song_highlight_color
        {
            get
            {
                return ResourceManager.GetString("setting label played song highlight color", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Instrument ähnelt.
        /// </summary>
        internal static string setting_label_select_instrument
        {
            get
            {
                return ResourceManager.GetString("setting label select instrument", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Language ähnelt.
        /// </summary>
        internal static string setting_label_select_ui_language
        {
            get
            {
                return ResourceManager.GetString("setting label select ui language", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Play speed ähnelt.
        /// </summary>
        internal static string setting_label_set_play_speed
        {
            get
            {
                return ResourceManager.GetString("setting label set play speed", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Progress ähnelt.
        /// </summary>
        internal static string setting_label_set_progress
        {
            get
            {
                return ResourceManager.GetString("setting label set progress", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show now playing info in echo chat ähnelt.
        /// </summary>
        internal static string setting_label_show_now_playing_info
        {
            get
            {
                return ResourceManager.GetString("setting label show now playing info", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delay ähnelt.
        /// </summary>
        internal static string setting_label_song_delay
        {
            get
            {
                return ResourceManager.GetString("setting label song delay", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Standalone playlist window ähnelt.
        /// </summary>
        internal static string setting_label_standalone_playlist_window
        {
            get
            {
                return ResourceManager.GetString("setting label standalone playlist window", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enable local clients sync ähnelt.
        /// </summary>
        internal static string setting_label_sync_clients
        {
            get
            {
                return ResourceManager.GetString("setting label sync clients", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die UI color ähnelt.
        /// </summary>
        internal static string setting_label_theme_color
        {
            get
            {
                return ResourceManager.GetString("setting label theme color", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tone mode ähnelt.
        /// </summary>
        internal static string setting_label_tone_mode
        {
            get
            {
                return ResourceManager.GetString("setting label tone mode", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Transpose ähnelt.
        /// </summary>
        internal static string setting_label_transpose_all
        {
            get
            {
                return ResourceManager.GetString("setting label transpose all", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Transpose per track ähnelt.
        /// </summary>
        internal static string setting_label_transpose_by_track
        {
            get
            {
                return ResourceManager.GetString("setting label transpose by track", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Adapt high/low pitch notes when they are out of range into 3 octaves we can play ähnelt.
        /// </summary>
        internal static string setting_tooltip_auto_adapt_notes
        {
            get
            {
                return ResourceManager.GetString("setting tooltip auto adapt notes", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Removes the pause at the beginning of a loaded midi ähnelt.
        /// </summary>
        internal static string setting_tooltip_auto_align_loaded_midi
        {
            get
            {
                return ResourceManager.GetString("setting tooltip auto align loaded midi", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Auto close MidiBard when exiting performance ähnelt.
        /// </summary>
        internal static string setting_tooltip_auto_close_when_performing
        {
            get
            {
                return ResourceManager.GetString("setting tooltip auto close when performing", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Try auto restart listening last used midi device ähnelt.
        /// </summary>
        internal static string setting_tooltip_auto_restart_listening
        {
            get
            {
                return ResourceManager.GetString("setting tooltip auto restart listening", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Auto disable background frame limit when entering performance mode and re-enable it when quit performance ähnelt.
        /// </summary>
        internal static string setting_tooltip_auto_set_background_frame_limit
        {
            get
            {
                return ResourceManager.GetString("setting tooltip auto set background frame limit", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Transpose/switch instrument based on first enabled midi track name (BMP rules) ähnelt.
        /// </summary>
        internal static string setting_tooltip_auto_switch_transpose_instrument_bmp_trackname
        {
            get
            {
                return ResourceManager.GetString("setting tooltip auto switch transpose instrument bmp trackname", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Auto transpose notes on demand. If you need this,
        ///please add #transpose number# before file name.
        ///E.g. #-12#demo.mid ähnelt.
        /// </summary>
        internal static string setting_tooltip_auto_transpose_by_file_name
        {
            get
            {
                return ResourceManager.GetString("setting tooltip auto transpose by file name", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Auto switch instrument on demand. If you need this,
        ///please add #instrument name# before file name.
        ///E.g. #harp#demo.mid ähnelt.
        /// </summary>
        internal static string setting_tooltip_label_auto_switch_instrument_by_file_name
        {
            get
            {
                return ResourceManager.GetString("setting tooltip label auto switch instrument by file name", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Change Midibard UI language ähnelt.
        /// </summary>
        internal static string setting_tooltip_language
        {
            get
            {
                return ResourceManager.GetString("setting tooltip language", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Use alternative note input method, May slightly reduce input latency but will affect guitar tone switching accuracy.
        ///Only recommended while using Midi keyboard. ähnelt.
        /// </summary>
        internal static string setting_tooltip_low_latency_mode
        {
            get
            {
                return ResourceManager.GetString("setting tooltip low latency mode", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Auto start ensemble when entering in-game party ensemble mode ähnelt.
        /// </summary>
        internal static string setting_tooltip_monitor_ensemble
        {
            get
            {
                return ResourceManager.GetString("setting tooltip monitor ensemble", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Play lyrics ähnelt.
        /// </summary>
        internal static string setting_tooltip_play_lyrics
        {
            get
            {
                return ResourceManager.GetString("setting_tooltip_play_lyrics", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Choose external midi input device. Right click to reset. ähnelt.
        /// </summary>
        internal static string setting_tooltip_select_input_device
        {
            get
            {
                return ResourceManager.GetString("setting tooltip select input device", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select current instrument
        ///Right click to quit performance mode ähnelt.
        /// </summary>
        internal static string setting_tooltip_select_instrument
        {
            get
            {
                return ResourceManager.GetString("setting tooltip select instrument", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Set the playing progress
        ///Right click to restart current playback ähnelt.
        /// </summary>
        internal static string setting_tooltip_set_progress
        {
            get
            {
                return ResourceManager.GetString("setting tooltip set progress", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Set the speed of events playing ähnelt.
        /// </summary>
        internal static string setting_tooltip_set_speed
        {
            get
            {
                return ResourceManager.GetString("setting tooltip set speed", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delay time before play next track. ähnelt.
        /// </summary>
        internal static string setting_tooltip_song_delay
        {
            get
            {
                return ResourceManager.GetString("setting tooltip song delay", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Allow midibard settings and midi file settings auto sync between all midibard instances on this pc ähnelt.
        /// </summary>
        internal static string setting_tooltip_sync_clients
        {
            get
            {
                return ResourceManager.GetString("setting tooltip sync clients", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Choose how MidiBard will handle MIDI channels and ProgramChange events (current only affects guitar tone changing) ähnelt.
        /// </summary>
        internal static string setting_tooltip_tone_mode
        {
            get
            {
                return ResourceManager.GetString("setting tooltip tone mode", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Transpose, measured by semitone.
        ///Right click to reset. ähnelt.
        /// </summary>
        internal static string setting_tooltip_transpose_all
        {
            get
            {
                return ResourceManager.GetString("setting tooltip transpose all", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Transpose per track, right click to reset all tracks&apos; transpose offset back to zero. ähnelt.
        /// </summary>
        internal static string setting_tooltip_transpose_by_track
        {
            get
            {
                return ResourceManager.GetString("setting tooltip transpose by track", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Playing: ähnelt.
        /// </summary>
        internal static string text_current_playing
        {
            get
            {
                return ResourceManager.GetString("text current playing", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ensemble running ähnelt.
        /// </summary>
        internal static string text_ensemble_mode_running
        {
            get
            {
                return ResourceManager.GetString("text ensemble mode running", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die (Copy) ähnelt.
        /// </summary>
        internal static string text_file_copy
        {
            get
            {
                return ResourceManager.GetString("text file copy", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Import in progress... ähnelt.
        /// </summary>
        internal static string text_Import_in_progress
        {
            get
            {
                return ResourceManager.GetString("text Import in progress", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Listening input device:  ähnelt.
        /// </summary>
        internal static string text_listening_midi_device
        {
            get
            {
                return ResourceManager.GetString("text listening midi device", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Midibard playlist ähnelt.
        /// </summary>
        internal static string text_midibard_playlist
        {
            get
            {
                return ResourceManager.GetString("text midibard playlist", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die New playlist ähnelt.
        /// </summary>
        internal static string text_new_playlist
        {
            get
            {
                return ResourceManager.GetString("text new playlist", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Import midi files to start performing! ähnelt.
        /// </summary>
        internal static string text_playlist_is_empty
        {
            get
            {
                return ResourceManager.GetString("text playlist is empty", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Playmode:  ähnelt.
        /// </summary>
        internal static string text_select_playmode
        {
            get
            {
                return ResourceManager.GetString("text select playmode", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Song name copied to clipboard ähnelt.
        /// </summary>
        internal static string text_song_name_copied_to_clipboard
        {
            get
            {
                return ResourceManager.GetString("text song name copied to clipboard", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Start event listening on  ähnelt.
        /// </summary>
        internal static string text_start_event_listening
        {
            get
            {
                return ResourceManager.GetString("text start event listening", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} tracks in playlist ähnelt.
        /// </summary>
        internal static string text_tracks_in_playlist
        {
            get
            {
                return ResourceManager.GetString("text tracks in playlist", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Off ähnelt.
        /// </summary>
        internal static string tone_mode_off
        {
            get
            {
                return ResourceManager.GetString("tone mode off", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Off: Does not take over game&apos;s guitar tone control. ähnelt.
        /// </summary>
        internal static string tone_mode_off_tooltip
        {
            get
            {
                return ResourceManager.GetString("tone mode off tooltip", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Override ähnelt.
        /// </summary>
        internal static string tone_mode_override
        {
            get
            {
                return ResourceManager.GetString("tone mode override", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Override by track: Assign guitar tone manually for each track and ignore ProgramChange events. ähnelt.
        /// </summary>
        internal static string tone_mode_override_tooltip
        {
            get
            {
                return ResourceManager.GetString("tone mode override tooltip", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Simple ähnelt.
        /// </summary>
        internal static string tone_mode_simple
        {
            get
            {
                return ResourceManager.GetString("tone mode simple", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Simple: Simple ProgramChange handling, ProgramChange event on any channel will change all channels&apos; program state. (This is BardMusicPlayer&apos;s default behavior.) ähnelt.
        /// </summary>
        internal static string tone_mode_simple_tooltip
        {
            get
            {
                return ResourceManager.GetString("tone mode simple tooltip", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Standard ähnelt.
        /// </summary>
        internal static string tone_mode_standard
        {
            get
            {
                return ResourceManager.GetString("tone mode standard", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Standard: Standard midi channel and ProgramChange handling, each channel will keep it&apos;s program state separately. ähnelt.
        /// </summary>
        internal static string tone_mode_standard_tooltip
        {
            get
            {
                return ResourceManager.GetString("tone mode standard tooltip", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Win32 file dialog ähnelt.
        /// </summary>
        internal static string w32_file_dialog
        {
            get
            {
                return ResourceManager.GetString("w32 file dialog", resourceCulture);
            }
        }

        internal static string setting_label_save_config_after_sync
        {
            get
            {
                return ResourceManager.GetString("setting label save config after sync", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Choose new playlist save location ähnelt.
        /// </summary>
        internal static string window_title_choose_new_playlist_save_location
        {
            get
            {
                return ResourceManager.GetString("window title choose new playlist save location", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die MidiBard local ensemble control ähnelt.
        /// </summary>
        internal static string window_title_ensemble_panel
        {
            get
            {
                return ResourceManager.GetString("window title ensemble panel", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die MidiBard Playlist ähnelt.
        /// </summary>
        internal static string window_title_standalone_playlist
        {
            get
            {
                return ResourceManager.GetString("window title standalone playlist", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die MidiBard track visualizer ähnelt.
        /// </summary>
        internal static string window_title_visualizor
        {
            get
            {
                return ResourceManager.GetString("window title visualizor", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Track selection
        ///MidiBard will only perform enabled tracks
        ///Left click to enable/disable a track, Right click to solo it ähnelt.
        /// </summary>
        internal static string window_tooltip_track_selection
        {
            get
            {
                return ResourceManager.GetString("window tooltip track selection", resourceCulture);
            }
        }

        internal static string setting_label_theme
        {
            get
            {
                return ResourceManager.GetString("setting_label_theme", resourceCulture);
            }
        }
        internal static string open_plugin_folder
        {
            get
            {
                return ResourceManager.GetString("open_plugin_folder", resourceCulture);
            }
        }
        internal static string open_plugin_config_file
        {
            get
            {
                return ResourceManager.GetString("open_plugin_config_file", resourceCulture);
            }
        }
        internal static string favorite_import_folders
        {
            get
            {
                return ResourceManager.GetString("favorite_import_folders", resourceCulture);
            }
        }
        internal static string add_folder
        {
            get
            {
                return ResourceManager.GetString("add_folder", resourceCulture);
            }
        }
        internal static string display_lyrics_tooltip
        {
            get
            {
                return ResourceManager.GetString("display_lyrics_tooltip", resourceCulture);
            }
        }
        internal static string select_chat_to_send_lyrics
        {
            get
            {
                return ResourceManager.GetString("select_chat_to_send_lyrics", resourceCulture);
            }
        }
        internal static string default_performer_folder
        {
            get
            {
                return ResourceManager.GetString("default_performer_folder", resourceCulture);
            }
        }
        internal static string ensemble_party_members
        {
            get
            {
                return ResourceManager.GetString("ensemble_party_members", resourceCulture);
            }
        }
        internal static string display_order
        {
            get
            {
                return ResourceManager.GetString("display_order", resourceCulture);
            }
        }
        internal static string available_party_members
        {
            get
            {
                return ResourceManager.GetString("available_party_members", resourceCulture);
            }
        }
        internal static string ensemble_compensation_mode
        {
            get
            {
                return ResourceManager.GetString("ensemble_compensation_mode", resourceCulture);
            }
        }
        internal static string lyrics
        {
            get
            {
                return ResourceManager.GetString("lyrics", resourceCulture);
            }
        }
        internal static string post_song_to_chat
        {
            get
            {
                return ResourceManager.GetString("post_song_to_chat", resourceCulture);
            }
        }
        internal static string auto_send_song_name_to_chat_on_play
        {
            get
            {
                return ResourceManager.GetString("auto_send_song_name_to_chat_on_play", resourceCulture);
            }
        }
        internal static string select_chat_to_send_song_name
        {
            get
            {
                return ResourceManager.GetString("select_chat_to_send_song_name", resourceCulture);
            }
        }
        internal static string song_name_regex_and_output_format
        {
            get
            {
                return ResourceManager.GetString("song_name_regex_and_output_format", resourceCulture);
            }
        }
        internal static string capture_regex
        {
            get
            {
                return ResourceManager.GetString("capture_regex", resourceCulture);
            }
        }
        internal static string output_format
        {
            get
            {
                return ResourceManager.GetString("output_format", resourceCulture);
            }
        }
        internal static string sanitize_song_name
        {
            get
            {
                return ResourceManager.GetString("sanitize_song_name", resourceCulture);
            }
        }
        internal static string find
        {
            get
            {
                return ResourceManager.GetString("find", resourceCulture);
            }
        }
        internal static string replace_by
        {
            get
            {
                return ResourceManager.GetString("replace_by", resourceCulture);
            }
        }
        internal static string play_on_multiple_devices
        {
            get
            {
                return ResourceManager.GetString("play_on_multiple_devices", resourceCulture);
            }
        }
        internal static string compensation_mode_option_default
        {
            get
            {
                return ResourceManager.GetString("compensation_mode_option_default", resourceCulture);
            }
        }
        internal static string compensation_mode_option_manual
        {
            get
            {
                return ResourceManager.GetString("compensation_mode_option_manual", resourceCulture);
            }
        }
        internal static string compensation_mode_option_none
        {
            get
            {
                return ResourceManager.GetString("compensation_mode_option_none", resourceCulture);
            }
        }
        internal static string chat_target_option_current
        {
            get
            {
                return ResourceManager.GetString("chat_target_option_current", resourceCulture);
            }
        }
        internal static string chat_target_option_say
        {
            get
            {
                return ResourceManager.GetString("chat_target_option_say", resourceCulture);
            }
        }
        internal static string chat_target_option_party
        {
            get
            {
                return ResourceManager.GetString("chat_target_option_party", resourceCulture);
            }
        }
        internal static string theme_default
        {
            get
            {
                return ResourceManager.GetString("theme_default", resourceCulture);
            }
        }
        internal static string theme_dark
        {
            get
            {
                return ResourceManager.GetString("theme_dark", resourceCulture);
            }
        }
        internal static string theme_modern_dark
        {
            get
            {
                return ResourceManager.GetString("theme_modern_dark", resourceCulture);
            }
        }
        internal static string theme_light
        {
            get
            {
                return ResourceManager.GetString("theme_light", resourceCulture);
            }
        }
        internal static string theme_ocean_fishing
        {
            get
            {
                return ResourceManager.GetString("theme_ocean_fishing", resourceCulture);
            }
        }
        internal static string theme_deepblue
        {
            get
            {
                return ResourceManager.GetString("theme_deepblue", resourceCulture);
            }
        }
        internal static string theme_catnip
        {
            get
            {
                return ResourceManager.GetString("theme_catnip", resourceCulture);
            }
        }
        internal static string theme_chocobo
        {
            get
            {
                return ResourceManager.GetString("theme_chocobo", resourceCulture);
            }
        }
        internal static string theme_dracula
        {
            get
            {
                return ResourceManager.GetString("theme_dracula", resourceCulture);
            }
        }
        internal static string theme_neon
        {
            get
            {
                return ResourceManager.GetString("theme_neon", resourceCulture);
            }
        }
        internal static string theme_purple
        {
            get
            {
                return ResourceManager.GetString("theme_purple", resourceCulture);
            }
        }
        internal static string theme_wine
        {
            get
            {
                return ResourceManager.GetString("theme_wine", resourceCulture);
            }
        }
        internal static string theme_barbie_pink
        {
            get
            {
                return ResourceManager.GetString("theme_barbie_pink", resourceCulture);
            }
        }
        internal static string theme_cotton_candy
        {
            get
            {
                return ResourceManager.GetString("theme_cotton_candy", resourceCulture);
            }
        }
        internal static string theme_tropical
        {
            get
            {
                return ResourceManager.GetString("theme_tropical", resourceCulture);
            }
        }
        internal static string theme_sunset
        {
            get
            {
                return ResourceManager.GetString("theme_sunset", resourceCulture);
            }
        }
        internal static string theme_orange
        {
            get
            {
                return ResourceManager.GetString("theme_orange", resourceCulture);
            }
        }
        internal static string anti_stack_note_option_off
        {
            get
            {
                return ResourceManager.GetString("anti_stack_note_option_off", resourceCulture);
            }
        }
        internal static string anti_stack_note_option_keep_first_note
        {
            get
            {
                return ResourceManager.GetString("anti_stack_note_option_keep_first_note", resourceCulture);
            }
        }
        internal static string anti_stack_note_option_keep_shortest_note
        {
            get
            {
                return ResourceManager.GetString("anti_stack_note_option_keep_shortest_note", resourceCulture);
            }
        }
        internal static string anti_stack_note_option_keep_longest_note
        {
            get
            {
                return ResourceManager.GetString("anti_stack_note_option_keep_longest_note", resourceCulture);
            }
        }
        internal static string change_folder
        {
            get
            {
                return ResourceManager.GetString("change_folder", resourceCulture);
            }
        }
        internal static string open_folder
        {
            get
            {
                return ResourceManager.GetString("open_folder", resourceCulture);
            }
        }
        internal static string tone_mode_tooltip_off
        {
            get
            {
                return ResourceManager.GetString("tone_mode_tooltip_off", resourceCulture);
            }
        }
        internal static string tone_mode_tooltip_standard
        {
            get
            {
                return ResourceManager.GetString("tone_mode_tooltip_standard", resourceCulture);
            }
        }
        internal static string tone_mode_tooltip_simple
        {
            get
            {
                return ResourceManager.GetString("tone_mode_tooltip_simple", resourceCulture);
            }
        }
        internal static string tone_mode_tooltip_override_by_track
        {
            get
            {
                return ResourceManager.GetString("tone_mode_tooltip_override_by_track", resourceCulture);
            }
        }
        internal static string tone_mode_tooltip_program_electric_guitar_mode
        {
            get
            {
                return ResourceManager.GetString("tone_mode_tooltip_program_electric_guitar_mode", resourceCulture);
            }
        }
        internal static string setting_label_ignore_default_performer
        {
            get
            {
                return ResourceManager.GetString("setting_label_ignore_default_performer", resourceCulture);
            }
        }
        internal static string setting_label_default_performer
        {
            get
            {
                return ResourceManager.GetString("setting_label_default_performer", resourceCulture);
            }
        }
        internal static string setting_label_default_playlist
        {
            get
            {
                return ResourceManager.GetString("setting_label_default_playlist", resourceCulture);
            }
        }
        internal static string default_playlist_folder
        {
            get
            {
                return ResourceManager.GetString("default_playlist_folder", resourceCulture);
            }
        }
        internal static string tone_mode_option_off
        {
            get
            {
                return ResourceManager.GetString("tone_mode_option_off", resourceCulture);
            }
        }
        internal static string tone_mode_option_standard
        {
            get
            {
                return ResourceManager.GetString("tone_mode_option_standard", resourceCulture);
            }
        }
        internal static string tone_mode_option_simple
        {
            get
            {
                return ResourceManager.GetString("tone_mode_option_simple", resourceCulture);
            }
        }
        internal static string tone_mode_option_override_by_track
        {
            get
            {
                return ResourceManager.GetString("tone_mode_option_override_by_track", resourceCulture);
            }
        }
        internal static string tone_mode_option_program_electric_guitar_mode
        {
            get
            {
                return ResourceManager.GetString("tone_mode_option_program_electric_guitar_mode", resourceCulture);
            }
        }
        internal static string setting_label_global_transpose
        {
            get
            {
                return ResourceManager.GetString("setting_label_global_transpose", resourceCulture);
            }
        }
        internal static string setting_label_show_hide_in_main_window
        {
            get
            {
                return ResourceManager.GetString("setting_label_show_hide_in_main_window", resourceCulture);
            }
        }
        internal static string setting_label_delay_between_songs
        {
            get
            {
                return ResourceManager.GetString("setting_label_delay_between_songs", resourceCulture);
            }
        }
        internal static string button_export_lrc_template
        {
            get
            {
                return ResourceManager.GetString("button_export_lrc_template", resourceCulture);
            }
        }
        internal static string settin_label_default_performer_tracks
        {
            get
            {
                return ResourceManager.GetString("settin_label_default_performer_tracks", resourceCulture);
            }
        }
        internal static string setting_label_empty
        {
            get
            {
                return ResourceManager.GetString("setting_label_empty", resourceCulture);
            }
        }

        // ----------------------------
        // new version
        // ----------------------------

        internal static string SettingsTitle
        {
            get
            {
                return ResourceManager.GetString("SettingsTitle", resourceCulture);
            }
        }
        internal static string SettingsGeneralTab
        {
            get
            {
                return ResourceManager.GetString("SettingsGeneralTab", resourceCulture);
            }
        }
        internal static string SearchInputLabel
        {
            get
            {
                return ResourceManager.GetString("SearchInputLabel", resourceCulture);
            }
        }
    }
}
